name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Get version value, set to env
        run: echo "PACKAGE_VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Download dependencies
        run: npm ci

      - name: Build MCLoader
        run: |
          npm run build
          npm run build:bin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: MCLoader
          path: dist
          if-no-files-found: error
          retention-days: 30

      - name: Upload release
        uses: softprops/action-gh-release@v1
          with:
            tag: ${{ env.PACKAGE_VERSION }}
            name: MCLoader ${{ env.PACKAGE_VERSION }}
            files: |
              dist/MCLoader.js
              dist/MCLoader_win64.exe
              dist/MCLoader_linux64
              dist/MCLoader_mac64
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}