name: Build

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ node -p "require('./package.json').version" }}

    steps:
      - uses: actions/checkout@v2

      # - name: Set version value
      #   run: |
      #     echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Download dependencies
        run: npm ci

      - name: Build MCLoader
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: MCLoader
          path: dist
          if-no-files-found: error
          retention-days: 30

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: MCLoader ${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/MCLoader.js
          asset_name: MCLoader.js
          asset_content_type: application/javascript